name: Compile On Push

on:
  push:
    tags:
    branches:
      - "main"

jobs:
  compile:
    uses: ./.github/workflows/compile-firmware-workflow-call.yaml
    with:
      git-ref: ${{ github.ref }}
      keymap: default
